spring.application.name=loja

spring.datasource.url=jdbc:postgresql://localhost:5432/pagamento
spring.datasource.username=postgres
spring.datasource.password=040501
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

server.port=8080
mercadopago.token=APP_USR-1905143522799161-041008-7d8d845c182492e2dedaee87e738d5b8-3326724141

spring.jpa.properties.hibernate.format_sql=true
