spring.application.name=loja

spring.datasource.url=jdbc:postgresql://localhost:5432/pagamento
spring.datasource.username=postgres
spring.datasource.password=040501
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

server.port=8080
mercadopago.token=TOKER_MERCADO_PAGO
